[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log

[program:app]
command=gunicorn -b :5000 -k gevent -w 1 app:app
user=appuser
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/app.log

[program:inference_server]
command=gunicorn -b :5000 -k gevent -w 1 triton:app
user=appuser
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/inference_server.log

[program:sage]
command=celery -A server.tasks.sage worker -E -Q training -P prefork -c 1 -l INFO -Ofair -n sage@%h
user=appuser
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/sage.log

[program:triton]
command=celery -A server.tasks.triton worker -E -Q development,testing,production -l INFO -Ofair -n triton@%h
user=appuser
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/celery.log