"""empty message

Revision ID: 0b898bb32a71
Revises: 95716fa1d947
Create Date: 2024-01-13 14:11:19.600826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b898bb32a71'
down_revision = '95716fa1d947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_trainings_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings')),
    sa.UniqueConstraint('task_id', name=op.f('uq_trainings_task_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    # ### end Alembic commands ###
