"""empty message

Revision ID: 28f05de52fcb
Revises: 68f8ed0f3917
Create Date: 2023-12-10 20:06:18.043494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f05de52fcb'
down_revision = '68f8ed0f3917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_languages_name'), ['name'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_models_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_token'), ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_models_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_languages_name'), type_='unique')

    # ### end Alembic commands ###
