"""empty message

Revision ID: 51c5f6b23b81
Revises: b3f1c07d92e4
Create Date: 2026-07-07 21:33:26.271856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5f6b23b81'
down_revision = 'b3f1c07d92e4'
branch_labels = None
depends_on = None


def upgrade():
    # No-op. This revision was autogenerated and originally (a) re-created the
    # ix_predictions_scope index already built by b3f1c07d92e4 and (b) dropped
    # the ``taskmeta``/``tasksetmeta`` tables. Those tables belong to celery's
    # SQLAlchemy result backend, not this app's metadata, so they are absent on
    # a fresh database and dropping them broke upgrades. Both were removed.
    pass


def downgrade():
    pass
