"""Initial migration

Revision ID: 6c511e96f142
Revises: 
Create Date: 2026-07-15 02:47:09.487486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c511e96f142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('name', name=op.f('uq_environments_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('token', name=op.f('uq_users_token'))
    )
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_models_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_entities_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_intents_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intents'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_predictions_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_predictions_scope', ['model_id', 'environment', 'created_at'], unique=False)

    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('version', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_trainings_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings')),
    sa.UniqueConstraint('task_id', name=op.f('uq_trainings_task_id'))
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=155), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('date_receive', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_instances_environment_id_environments')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_instances_model_id_models')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_instances_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('api_key', name=op.f('uq_instances_api_key')),
    sa.UniqueConstraint('task_id', name=op.f('uq_instances_task_id'))
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_slots_entity_id_entities')),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], name=op.f('fk_slots_intent_id_intents')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_slots_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots'))
    )
    op.create_table('utterances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], name=op.f('fk_utterances_intent_id_intents')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_utterances_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utterances'))
    )
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utterances_text'), ['text'], unique=False)

    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_values_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_values'))
    )
    op.create_table('synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['value_id'], ['values.id'], name=op.f('fk_synonyms_value_id_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synonyms'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utterance_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_tags_entity_id_entities')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_tags_slot_id_slots')),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterances.id'], name=op.f('fk_tags_utterance_id_utterances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('synonyms')
    op.drop_table('values')
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utterances_text'))

    op.drop_table('utterances')
    op.drop_table('slots')
    op.drop_table('instances')
    op.drop_table('trainings')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_scope')

    op.drop_table('predictions')
    op.drop_table('intents')
    op.drop_table('entities')
    op.drop_table('models')
    op.drop_table('users')
    op.drop_table('environments')
    # ### end Alembic commands ###
