"""empty message

Revision ID: 76a23ef3ac76
Revises: d037f2d6ab1c
Create Date: 2024-01-12 13:56:33.336082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a23ef3ac76'
down_revision = 'd037f2d6ab1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_labels_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels'))
    )
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_texts_label_id_labels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_texts'))
    )
    op.drop_table('languages')
    op.drop_table('language_models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('language_id', sa.INTEGER(), nullable=True),
    sa.Column('model_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_languages_name')
    )
    op.drop_table('texts')
    op.drop_table('labels')
    # ### end Alembic commands ###
