"""empty message

Revision ID: 95716fa1d947
Revises: 3466571a4e11
Create Date: 2024-01-12 20:52:44.691466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95716fa1d947'
down_revision = '3466571a4e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utterances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_utterances_label_id_labels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utterances'))
    )
    op.drop_table('texts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label_id', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name='fk_texts_label_id_labels'),
    sa.PrimaryKeyConstraint('id', name='pk_texts')
    )
    op.drop_table('utterances')
    # ### end Alembic commands ###
