"""empty message

Revision ID: 9e9ec0673765
Revises: f0c2f886bd1b
Create Date: 2026-04-28 22:29:10.067695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9ec0673765'
down_revision = 'f0c2f886bd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        # Nullable to match the model (Model.type is nullable with a Python-side
        # default); server_default only backfills existing rows on upgrade.
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True, server_default='text_classification'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
