"""empty message

Revision ID: a02d9b962c2e
Revises: 0b898bb32a71
Create Date: 2024-01-13 16:49:49.430897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02d9b962c2e'
down_revision = '0b898bb32a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utterances_text'), ['text'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utterances_text'))

    # ### end Alembic commands ###
