"""empty message

Revision ID: bc66d2653853
Revises: 9c4c0bbaf40f
Create Date: 2026-07-10 11:30:33.336108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc66d2653853'
down_revision = '9c4c0bbaf40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_predictions_scope'))
        batch_op.drop_constraint(batch_op.f('fk_predictions_model_id_models'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_predictions_instance_id_instances'), 'instances', ['instance_id'], ['id'])
        batch_op.drop_column('version')
        batch_op.drop_column('label')
        batch_op.drop_column('error')
        batch_op.drop_column('score')
        batch_op.drop_column('model_id')
        batch_op.drop_column('environment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('model_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_predictions_instance_id_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_predictions_model_id_models'), 'models', ['model_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_predictions_scope'), ['model_id', 'environment', 'created_at'], unique=False)
        batch_op.drop_column('instance_id')

    # ### end Alembic commands ###
