"""empty message

Revision ID: d037f2d6ab1c
Revises: 28f05de52fcb
Create Date: 2023-12-10 23:40:11.883724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd037f2d6ab1c'
down_revision = '28f05de52fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_models', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
