"""empty message

Revision ID: d62d61f7a8f0
Revises: 699d482c1005
Create Date: 2026-06-13 21:20:09.527312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62d61f7a8f0'
down_revision = '699d482c1005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('name', name=op.f('uq_environments_name'))
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=155), nullable=True),
    sa.Column('date_receive', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_instances_environment_id_environments')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_instances_model_id_models')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_instances_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('task_id', name=op.f('uq_instances_task_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    op.drop_table('environments')
    # ### end Alembic commands ###
