"""empty message

Revision ID: f0c2f886bd1b
Revises: 2c102f647f69
Create Date: 2024-01-23 23:33:35.797091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2f886bd1b'
down_revision = '2c102f647f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Numeric(precision=3, scale=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
